server:
  port: 8083

spring:
  application:
    name: backoffice-countries

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8084/oauth/check_token
    client:
      client-id: CLIENT
      client-secret: SECRET

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

